var InitialStatePuzzle = [
    {
        id: 1,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 2,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 3,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 4,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 5,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 6,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 7,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 8,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 9,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 10,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 11,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 12,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 13,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 14,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 15,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
    {
        id: 16,
        innerArray: [
            {
                id: 1,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 2,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 3,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 4,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 5,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 6,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 7,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 8,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
            {
                id: 9,
                isOpened: false,
                isFlagged: false,
                val: 0,
            },
        ],
    },
]

export default InitialStatePuzzle